/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'completed' : IDL.Bool,
  'category' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'completedAt' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChecklistItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteChecklistItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklistItemsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChecklistItem)],
      ['query'],
    ),
  'getCurrentInvoiceCounter' : IDL.Func([], [IDL.Nat], ['query']),
  'getLowStockThreshold' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextInvoiceNumber' : IDL.Func([], [IDL.Nat], []),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetChecklistForNewDay' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
  'toggleChecklistItem' : IDL.Func([IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'completed' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'completedAt' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChecklistItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteChecklistItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklistItemsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChecklistItem)],
        ['query'],
      ),
    'getCurrentInvoiceCounter' : IDL.Func([], [IDL.Nat], ['query']),
    'getLowStockThreshold' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextInvoiceNumber' : IDL.Func([], [IDL.Nat], []),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetChecklistForNewDay' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
    'toggleChecklistItem' : IDL.Func([IDL.Nat], [], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };