/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'completed' : boolean,
  'category' : string,
}
export interface Task {
  'id' : bigint,
  'status' : string,
  'completedAt' : string,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : string,
  'dueDate' : string,
  'description' : string,
  'priority' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChecklistItem' : ActorMethod<[string, string, string], bigint>,
  'addTask' : ActorMethod<[string, string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteChecklistItem' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklistItemsByDate' : ActorMethod<[string], Array<ChecklistItem>>,
  'getCurrentInvoiceCounter' : ActorMethod<[], bigint>,
  'getLowStockThreshold' : ActorMethod<[], bigint>,
  'getNextInvoiceNumber' : ActorMethod<[], bigint>,
  'getSharedData' : ActorMethod<[string], [] | [string]>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByAssignee' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetChecklistForNewDay' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLowStockThreshold' : ActorMethod<[bigint], undefined>,
  'setSharedData' : ActorMethod<[string, string], undefined>,
  'toggleChecklistItem' : ActorMethod<[bigint], undefined>,
  'updateTask' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
